/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as HermesCollectionNFTContractJson } from "../HermesCollectionNFT.ral.json";
import { getContractByCodeHash } from "./contracts";
import { DIAOracleValue, AllStructs } from "./types";

// Custom types for the contract
export namespace HermesCollectionNFTTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{ nftUri: HexString }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> =
    Callss["length"] extends 1
      ? MultiCallResults<Callss[0]>
      : { [index in keyof Callss]: MultiCallResults<Callss[index]> };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{ nftUri: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  HermesCollectionNFTInstance,
  HermesCollectionNFTTypes.Fields
> {
  encodeFields(fields: HermesCollectionNFTTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  consts = {
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("0"),
      NFTNotFound: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): HermesCollectionNFTInstance {
    return new HermesCollectionNFTInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<HermesCollectionNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<HermesCollectionNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        HermesCollectionNFTTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        HermesCollectionNFTTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        HermesCollectionNFTTypes.Fields,
        { nftUri: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const HermesCollectionNFT = new Factory(
  Contract.fromJson(
    HermesCollectionNFTContractJson,
    "",
    "86f278d2de249eca00d0c68f12167da0c1a54c02eaa8c148f89e659ae7cf11af",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class HermesCollectionNFTInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<HermesCollectionNFTTypes.State> {
    return fetchContractState(HermesCollectionNFT, this);
  }

  view = {
    getCollectionUri: async (
      params?: HermesCollectionNFTTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      HermesCollectionNFTTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        HermesCollectionNFT,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: HermesCollectionNFTTypes.CallMethodParams<"totalSupply">
    ): Promise<HermesCollectionNFTTypes.CallMethodResult<"totalSupply">> => {
      return callMethod(
        HermesCollectionNFT,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: HermesCollectionNFTTypes.CallMethodParams<"nftByIndex">
    ): Promise<HermesCollectionNFTTypes.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        HermesCollectionNFT,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: HermesCollectionNFTTypes.CallMethodParams<"validateNFT">
    ): Promise<HermesCollectionNFTTypes.CallMethodResult<"validateNFT">> => {
      return callMethod(
        HermesCollectionNFT,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: HermesCollectionNFTTypes.CallMethodParams<"mint">
    ): Promise<HermesCollectionNFTTypes.CallMethodResult<"mint">> => {
      return callMethod(
        HermesCollectionNFT,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: HermesCollectionNFTTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      HermesCollectionNFTTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        HermesCollectionNFT,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: HermesCollectionNFTTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      HermesCollectionNFTTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        HermesCollectionNFT,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: HermesCollectionNFTTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      HermesCollectionNFTTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(HermesCollectionNFT, this, "nftByIndex", params);
    },
    validateNFT: async (
      params: HermesCollectionNFTTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      HermesCollectionNFTTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        HermesCollectionNFT,
        this,
        "validateNFT",
        params
      );
    },
    mint: async (
      params: HermesCollectionNFTTypes.SignExecuteMethodParams<"mint">
    ): Promise<HermesCollectionNFTTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(HermesCollectionNFT, this, "mint", params);
    },
  };

  async multicall<Callss extends HermesCollectionNFTTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<HermesCollectionNFTTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      HermesCollectionNFT,
      this,
      callss,
      getContractByCodeHash
    )) as HermesCollectionNFTTypes.MulticallReturnType<Callss>;
  }
}
