/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as HermesNFTContractJson } from "../HermesNFT.ral.json";
import { getContractByCodeHash } from "./contracts";
import { DIAOracleValue, AllStructs } from "./types";

// Custom types for the contract
export namespace HermesNFTTypes {
  export type Fields = {
    collectionId: HexString;
    nftIndex: bigint;
    uri: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> =
    Callss["length"] extends 1
      ? MultiCallResults<Callss[0]>
      : { [index in keyof Callss]: MultiCallResults<Callss[index]> };

  export interface SignExecuteMethodTable {
    getTokenUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCollectionIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  HermesNFTInstance,
  HermesNFTTypes.Fields
> {
  encodeFields(fields: HermesNFTTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): HermesNFTInstance {
    return new HermesNFTInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<HermesNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenUri", params, getContractByCodeHash);
    },
    getCollectionIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<HermesNFTTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint]>> => {
      return testMethod(
        this,
        "getCollectionIndex",
        params,
        getContractByCodeHash
      );
    },
  };
}

// Use this object to test and deploy the contract
export const HermesNFT = new Factory(
  Contract.fromJson(
    HermesNFTContractJson,
    "",
    "4897086210869e612d82995b765a447c5319a55a56e8a0c3c07b4d9ca81e15b1",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class HermesNFTInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<HermesNFTTypes.State> {
    return fetchContractState(HermesNFT, this);
  }

  view = {
    getTokenUri: async (
      params?: HermesNFTTypes.CallMethodParams<"getTokenUri">
    ): Promise<HermesNFTTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        HermesNFT,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionIndex: async (
      params?: HermesNFTTypes.CallMethodParams<"getCollectionIndex">
    ): Promise<HermesNFTTypes.CallMethodResult<"getCollectionIndex">> => {
      return callMethod(
        HermesNFT,
        this,
        "getCollectionIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getTokenUri: async (
      params: HermesNFTTypes.SignExecuteMethodParams<"getTokenUri">
    ): Promise<HermesNFTTypes.SignExecuteMethodResult<"getTokenUri">> => {
      return signExecuteMethod(HermesNFT, this, "getTokenUri", params);
    },
    getCollectionIndex: async (
      params: HermesNFTTypes.SignExecuteMethodParams<"getCollectionIndex">
    ): Promise<
      HermesNFTTypes.SignExecuteMethodResult<"getCollectionIndex">
    > => {
      return signExecuteMethod(HermesNFT, this, "getCollectionIndex", params);
    },
  };

  async multicall<Callss extends HermesNFTTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<HermesNFTTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      HermesNFT,
      this,
      callss,
      getContractByCodeHash
    )) as HermesNFTTypes.MulticallReturnType<Callss>;
  }
}
